_base_: [
  './_base_/default.yaml',
  './_base_/dataset/train_openimage_eval_kodak.yaml',
  './_base_/model/hyperprior_charm_dual_cond_vic_model_vq_f8_n256.yaml'
]

trainer:
  type: RateDistortionVqCodeTrainer

model:
  type: HyperpriorCharmVicModel
  enc_vq_input: onehot_indices

subnet:
  encoder:
    _delete_: True
    type: ElicVqCatScEncoder
    in_ch: 3
    out_ch: 192 # bottleneck_y
    main_ch: 192
    proj_init: False
    block_mid_ch: 96
    input_feat_ch: 260 # 256 + 4
  decoder:
    _delete_: True
    type: ElicFeatFusionDecoder
    in_ch: 192 # bottleneck_y
    block_mid_ch: 96
    out_ch: 3
    main_ch: 192
    use_tanh: False
    feat_layer_name: block1
    fusion_layer_dict:
      block1: block_1_8
      block2: block_1_4
      block3: block_1_2

optim:
  clip_max_norm: 1.0
  g_optimizer:
    type: Adam
    lr: 0.0001
  g_scheduler:
    _delete_: True
    type: LinearWarmupScheduler
    warmup_iters: 50000
    warmup_factor: 0.1
  aux_optimizer:
    type: Adam
    lr: 0.001

start_iter: 0
total_iter: 500000

loss:
  rate_loss:
    type: RateLoss
    loss_weight: 0.04
  distortion_loss:
    type: MSELoss
    loss_weight: 50
    normalize_img: True
    mse_scale: '0_1'
  perceptual_loss:
    type: LPIPSLoss
    net: alex
    loss_weight: 1.0
  code_distortion_loss:
    type: VanillaMSELoss
    loss_weight: 0.1
  code_ce_loss:
    type: FocalCrossEntropyLoss
    gamma: 2.0
    loss_weight: 0.05