_base_: ./exp1_stage1_3.yaml

load_checkpoint:
  exp: exp1_stage1_3
  iter: 500000
  load_discriminator: True
  load_scheduler: False
  load_optimizer: True
  new_g_lr: 0.0001
  new_d_lr: 0.0001
  strict: True

model:
  use_selected_beta_pairs: true
  # pairs decided by `score = PSNR * 2 - FID`
  selected_beta_rate: [
    2.29, # 0.050 bpp
    1.51, # 0.075 bpp
    1.12, # 0.100 bpp
    0.62, # 0.125 bpp
    0.16, # 0.150 bpp
  ]
  selected_beta_vq: [
    3.00, # 0.050 bpp
    2.25, # 0.075 bpp
    2.00, # 0.100 bpp
    1.50, # 0.125 bpp
    1.00, # 0.150 bpp
  ]

keep_step: [
  400000,
  500000,
]
total_iter: 500000

optim:
  g_scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.1
  d_scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.1
