model:
  type: HyperpriorCharmDualCondVicModel
  enc_vq_input: onehot_indices
subnet:
  _delete_: True
  encoder:
    type: ElicDualBetaFtVqScEncoder
    in_ch: 3
    out_ch: 192 # bottleneck_y
    main_ch: 192
    block_mid_ch: 96
    input_feat_ch: 260 # 256 + 4
    proj_init: False
    max_beta_1: null
    max_beta_2: null
    include_x: true
    cond_ch: 128
    L: 10
    use_pi: False
  decoder: 
    type: ElicDualBetaFtFeatFusionDecoder
    block_mid_ch: 96
    in_ch: 192 # bottleneck_y
    out_ch: 3
    main_ch: 192
    use_tanh: False
    feat_layer_name: block1
    max_beta_1: null
    max_beta_2: null
    include_x: true
    cond_ch: 128
    L: 10
    use_pi: False
    fusion_layer_dict:
      # _delete_: True
      block1: block_1_8
      block2: block_1_4
      block3: block_1_2
  hyperencoder:
    type: Minnen20HyperEncoder
    bottleneck_y: 192
    bottleneck_z: 192
  hyperdecoder:
    type: Minnen20HyperDecoder
    bottleneck_z: 192
    hyper_out_ch: 256
  context_model:
    type: Minnen20CharmContextModel
    num_slices: 6
    bottleneck_y: 192
    hyper_out_ch: 256
    max_support_slices: 4
  entropy_model_z:
    type: SteEntropyBottleneck
    channels: 192 # bottleneck_z
  entropy_model_y:
    type: SteGaussianMeanScaleConditional
    scale_bound: 0.11
  fusion_module:
    fuse_type: sft
    fuse_scedule_dict:
      block_1_8:
        dec_ch: 512
        cond_ch: 192
        mid_ch: 512
      block_1_4:
        dec_ch: 256
        cond_ch: 192
        mid_ch: 256
      block_1_2:
        dec_ch: 256
        cond_ch: 192
        mid_ch: 256
  vq_estimator: 
    type: DualBlockSwinVqEstimator
    input_resolution: [32, 32]
    in_ch: 192
    main_ch: 128
    n_embed: 256
    embed_dim: 4
    num_swin_blocks: 3 # 4 -> 3
    blk_depth: 3 # 6 -> 3
    use_upsample: false
  vq_model:
    ckpt_path: null
    ## parameters
    embed_dim: 4
    n_embed: 256
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 2
      attn_resolutions: [32]
      dropout: 0.0
    lossconfig:
      target: torch.nn.Identity